### PR TITLE
Add automatic publish to PyPI

### PR DESCRIPTION
**Pull request by beveradb**
Thanks for your work on this project @Jeronymous!

Just as a heads up, there's an existing PyPI project for `whisper-timestamped`, set up and published to about 5 months ago by @boseguera: https://pypi.org/project/whisper-timestamped/

While I appreciate that project wasn't set up by you, I've personally found it very useful for pulling in `whisper-timestamped` as a dependency to my other projects (e.g. [https://github.com/karaokenerds/python-lyrics-transcriber](python-lyrics-transcriber)).

I've now gained joint owner privileges on that PyPI project (thanks Benny!), and I'd love to set up this repo to auto-publish builds to PyPI whenever new commits are merged to master, so folks like me who may have pulled in the dependency using `pip install whisper-timestamped` can get the latest code more easily 😄 

The github actions package this PR proposes just needs a PyPI token (which I can generate and provide you with separately using my own account, or I can invite you as an owner of the PyPI project to use your own token), configured as env var `PYPI_API_TOKEN` in the github repo settings:
https://github.com/marketplace/actions/python-auto-release-pypi-github

What do you think? 🙏

### CODE REVIEW

**Comment by beveradb** [comment]
FYI for now I've just published an updated package to PyPI: 
https://pypi.org/project/whisper-timestamped/#history

**Comment by bennyo27** [comment]
Hello, this is boseguera, I also wanted to mention that I tried reaching out to linto-ai about me setting up this pypi package but never got an email back.

**Comment by Jeronymous** [comment]
Thanks a lot @beveradb 
Excellent. Yes let's ship things so that they can be installed easily with pip :)

You can provide the token to me by email (which you should find in the git commits of this repo).
I guess I will also have to add the information in the README.

And sorry @bennyo27 I am investigating who is in charge of treating mails sent to hello at linto.ai and why you got no answer. Somebody should come back to you.

**Comment by bennyo27** [comment]
> Thanks a lot @beveradb 
> Excellent. Yes let's ship things so that they can be installed easily with pip :)
> 
> You can provide the token to me by email (which you should find in the git commits of this repo).
> I guess I will also have to add the information in the README.
> 
> And sorry @bennyo27 I am investigating who is in charge of treating mails sent to hello at linto.ai and why you got no answer. Somebody should come back to you.
> 

Oh thank you so much!

**Comment by Jeronymous** [comment]
@beveradb Any news on that? I haven't received any email with a token.
 
You can use the email address hello_at_linto.ai for that.

**Comment by bennyo27** [comment]
> @beveradb Any news on that? I haven't received any email with a token.
> 
> You can use the email address hello_at_linto.ai for that.

I can send you the email with the token, perhaps @beveradb is on break? What is the exact email hello@linto.ai?

**Comment by beveradb** [comment]
Sorry for the slow reply, just had a busy weekend!

Just emailed you (on your gmail from commits) with the token and instructions to decode and set as the `PYPI_API_TOKEN` github actions repository secret.

Thanks again!

**Comment by bennyo27** [comment]
No problem! Yes you can send me what you want to add to that page or I can
make you an owner of the pypi page also.

**Comment by Jeronymous** [comment]
Better if I can be owner of the pypi page :)
(as I will probably want to modify things by iterations, depending on how things look and how the library evolves)

**Comment by Jeronymous** [comment]
OK! I will have to retry later :/ "PyPI new user registration temporarily suspended"

**Pull request merged**
